name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mkumor/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true mkumor/react-test npm test

      - run: docker build -t mkumor/multi-client:v2 ./client
      - run: docker build -t mkumor/multi-nginx:v2 ./nginx
      - run: docker build -t mkumor/multi-server:v2 ./server
      - run: docker build -t mkumor/multi-worker:v2 ./worker

      - run: docker push mkumor/multi-client:v2
      - run: docker push mkumor/multi-nginx:v2
      - run: docker push mkumor/multi-server:v2
      - run: docker push mkumor/multi-worker:v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-429583250310
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
